"""init

Revision ID: 2ccfc81cc629
Revises: 
Create Date: 2025-12-26 22:43:31.993329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ccfc81cc629'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sei_processos_temp_etl',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('protocol', sa.String(length=50), nullable=False),
    sa.Column('id_protocolo', sa.String(length=50), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('tipo_procedimento', sa.String(length=255), nullable=True),
    sa.Column('unidade', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sei_processos_temp_etl_id_protocolo'), 'sei_processos_temp_etl', ['id_protocolo'], unique=False)
    op.create_index(op.f('ix_sei_processos_temp_etl_protocol'), 'sei_processos_temp_etl', ['protocol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sei_processos_temp_etl_protocol'), table_name='sei_processos_temp_etl')
    op.drop_index(op.f('ix_sei_processos_temp_etl_id_protocolo'), table_name='sei_processos_temp_etl')
    op.drop_table('sei_processos_temp_etl')
    # ### end Alembic commands ###
