"""create etl tables

Revision ID: fd65061c8b08
Revises: 2ccfc81cc629
Create Date: 2025-12-26 23:50:42.600394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd65061c8b08'
down_revision: Union[str, None] = '2ccfc81cc629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sei_etl_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('protocol', sa.String(length=50), nullable=False),
    sa.Column('metadata_status', sa.String(length=50), nullable=True),
    sa.Column('metadata_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_error', sa.Text(), nullable=True),
    sa.Column('documentos_status', sa.String(length=50), nullable=True),
    sa.Column('documentos_total', sa.Integer(), nullable=True),
    sa.Column('documentos_downloaded', sa.Integer(), nullable=True),
    sa.Column('documentos_error', sa.Text(), nullable=True),
    sa.Column('andamentos_status', sa.String(length=50), nullable=True),
    sa.Column('andamentos_total', sa.Integer(), nullable=True),
    sa.Column('andamentos_error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('last_retry_at', sa.DateTime(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sei_etl_status_andamentos_status'), 'sei_etl_status', ['andamentos_status'], unique=False)
    op.create_index(op.f('ix_sei_etl_status_documentos_status'), 'sei_etl_status', ['documentos_status'], unique=False)
    op.create_index(op.f('ix_sei_etl_status_metadata_status'), 'sei_etl_status', ['metadata_status'], unique=False)
    op.create_index(op.f('ix_sei_etl_status_protocol'), 'sei_etl_status', ['protocol'], unique=True)
    op.create_table('sei_processos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('protocol', sa.String(length=50), nullable=False),
    sa.Column('id_protocolo', sa.BigInteger(), nullable=True),
    sa.Column('id_unidade', sa.Integer(), nullable=True),
    sa.Column('tipo_procedimento', sa.String(length=255), nullable=True),
    sa.Column('especificacao', sa.Text(), nullable=True),
    sa.Column('nivel_acesso', sa.String(length=50), nullable=True),
    sa.Column('hipotese_legal', sa.Text(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('data_abertura', sa.DateTime(), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.Column('interessados', sa.JSON(), nullable=True),
    sa.Column('assuntos', sa.JSON(), nullable=True),
    sa.Column('unidade_geradora', sa.String(length=255), nullable=True),
    sa.Column('unidade_atual', sa.String(length=255), nullable=True),
    sa.Column('raw_api_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sei_processos_data_abertura'), 'sei_processos', ['data_abertura'], unique=False)
    op.create_index(op.f('ix_sei_processos_id_protocolo'), 'sei_processos', ['id_protocolo'], unique=False)
    op.create_index(op.f('ix_sei_processos_protocol'), 'sei_processos', ['protocol'], unique=True)
    op.create_table('sei_andamentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('processo_id', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=50), nullable=False),
    sa.Column('id_andamento', sa.BigInteger(), nullable=True),
    sa.Column('sequencia', sa.Integer(), nullable=True),
    sa.Column('tipo_andamento', sa.String(length=255), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tarefa', sa.String(length=50), nullable=True),
    sa.Column('usuario', sa.String(length=255), nullable=True),
    sa.Column('unidade_origem', sa.String(length=255), nullable=True),
    sa.Column('unidade_destino', sa.String(length=255), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('atributos', sa.JSON(), nullable=True),
    sa.Column('raw_api_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['processo_id'], ['sei_processos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sei_andamentos_data_hora'), 'sei_andamentos', ['data_hora'], unique=False)
    op.create_index(op.f('ix_sei_andamentos_processo_id'), 'sei_andamentos', ['processo_id'], unique=False)
    op.create_index(op.f('ix_sei_andamentos_protocol'), 'sei_andamentos', ['protocol'], unique=False)
    op.create_table('sei_documentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('processo_id', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=50), nullable=False),
    sa.Column('id_documento', sa.BigInteger(), nullable=False),
    sa.Column('numero_documento', sa.String(length=50), nullable=True),
    sa.Column('tipo_documento', sa.String(length=255), nullable=True),
    sa.Column('serie', sa.String(length=255), nullable=True),
    sa.Column('numero', sa.String(length=50), nullable=True),
    sa.Column('data_documento', sa.DateTime(), nullable=True),
    sa.Column('usuario_gerador', sa.String(length=255), nullable=True),
    sa.Column('unidade_geradora', sa.String(length=255), nullable=True),
    sa.Column('assinado', sa.Boolean(), nullable=True),
    sa.Column('assinantes', sa.JSON(), nullable=True),
    sa.Column('nivel_acesso', sa.String(length=50), nullable=True),
    sa.Column('tamanho_bytes', sa.BigInteger(), nullable=True),
    sa.Column('formato', sa.String(length=50), nullable=True),
    sa.Column('hash_sha256', sa.String(length=64), nullable=True),
    sa.Column('minio_bucket', sa.String(length=100), nullable=True),
    sa.Column('minio_path', sa.String(length=500), nullable=True),
    sa.Column('download_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('download_attempts', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('raw_api_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['processo_id'], ['sei_processos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sei_documentos_id_documento'), 'sei_documentos', ['id_documento'], unique=True)
    op.create_index(op.f('ix_sei_documentos_processo_id'), 'sei_documentos', ['processo_id'], unique=False)
    op.create_index(op.f('ix_sei_documentos_protocol'), 'sei_documentos', ['protocol'], unique=False)
    op.create_index(op.f('ix_sei_documentos_status'), 'sei_documentos', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sei_documentos_status'), table_name='sei_documentos')
    op.drop_index(op.f('ix_sei_documentos_protocol'), table_name='sei_documentos')
    op.drop_index(op.f('ix_sei_documentos_processo_id'), table_name='sei_documentos')
    op.drop_index(op.f('ix_sei_documentos_id_documento'), table_name='sei_documentos')
    op.drop_table('sei_documentos')
    op.drop_index(op.f('ix_sei_andamentos_protocol'), table_name='sei_andamentos')
    op.drop_index(op.f('ix_sei_andamentos_processo_id'), table_name='sei_andamentos')
    op.drop_index(op.f('ix_sei_andamentos_data_hora'), table_name='sei_andamentos')
    op.drop_table('sei_andamentos')
    op.drop_index(op.f('ix_sei_processos_protocol'), table_name='sei_processos')
    op.drop_index(op.f('ix_sei_processos_id_protocolo'), table_name='sei_processos')
    op.drop_index(op.f('ix_sei_processos_data_abertura'), table_name='sei_processos')
    op.drop_table('sei_processos')
    op.drop_index(op.f('ix_sei_etl_status_protocol'), table_name='sei_etl_status')
    op.drop_index(op.f('ix_sei_etl_status_metadata_status'), table_name='sei_etl_status')
    op.drop_index(op.f('ix_sei_etl_status_documentos_status'), table_name='sei_etl_status')
    op.drop_index(op.f('ix_sei_etl_status_andamentos_status'), table_name='sei_etl_status')
    op.drop_table('sei_etl_status')
    # ### end Alembic commands ###
